### ISSUE TITLE
Translate README to pt-BR

### ISSUE THREAD

**Issue by felipefontoura** [internetsistemas/brazilian_forgery#5]
In accordance with @thiagodepaula Brazilian Forgery speaks only EN (duh) in the README. But it's not for Brazilian?

**Comment by brunoocasali** [comment]
I aggree with you, but I think is need to use both versions, in English and Portuguese!

What do you think ?

ps: I've started a new PR with the changes but I'm not concluded yet! #7

**Comment by felipefontoura** [comment]
Yes the both versions :facepunch:

**Comment by brunoocasali** [comment]
Done! See the Pull Request #7, What do you think?!

**Comment by brunoocasali** [comment]
Closing change already done!
